# https://rocketmq.apache.org/docs/quickStart/01quickstart/
rocketmq:
  name-server: ${rocketmq.address}
  producer:
    group: ${spring.application.name}-producer
  consumer:
    group: ${spring.application.name}-consumer