# https://rocketmq.apache.org/docs/quickStart/01quickstart/
rocketmq:
  name-server: ${rocketmq.address}
  producer:
    group: producer-${spring.application.name}
  consumer:
    group: consumer-${spring.application.name}