# https://cn.dubbo.apache.org/zh-cn/overview/what/
dubbo:
  registry:
    # 填写正确的 ip 地址
    address: ${dubbo.address}
    # all: 注入接口和实例
    register-mode: all
    parameters:
      # 填写 namespace 后在 nacas 对应命名空间就能发现服务了
      namespace: ${nacos.config.namespace}
      username: ${nacos.username}
      password: ${nacos.password}
      register-consumer-url: true
  protocol:
    name: tri
    port: 50051