spring:
  application:
    name: i-cloud

  profiles:
    include:
      - app
      - nacos
      - dubbo
      - redis
      - datasource
      - mybatis
      - powerjob
      - seata
      - rocketmq

# 解决 cloud 版本兼容问题
  cloud:
    compatibility-verifier:
      enabled: false

logging:
  file:
    path: classpath:logback-spring.xml