spring:
  config:
    import: optional:nacos:application-${spring.application.name}.yml
  cloud:
    nacos:
      username: ${nacos.username}
      password: ${nacos.password}
      server-addr: ${nacos.address}
      config:
        namespace: ${nacos.config.namespace}
      discovery:
        namespace: ${nacos.discovery.namespace}