# http://www.powerjob.tech/
powerjob:
  worker:
    app-name: ${spring.application.name}
    server-address: ${powerjob.address}
    protocol: http
    store-strategy: disk
    max-result-length: 4096
    max-appended-wf-context-length: 4096
    max-lightweight-task-num: 1024
    max-heavy-task-num: 64