nacos:
  address: 192.168.145.133:8848
  username: nacos
  password: nacos
  config:
    namespace: public
  discovery:
    namespace: public

spring:
  config:
    import: optional:nacos:${spring.application.name}.appplication.yml
  cloud:
    nacos:
      username: ${nacos.username}
      password: ${nacos.password}
      server-addr: ${nacos.address}
      config:
        namespace: ${nacos.config.namespace}
      discovery:
        namespace: ${nacos.discovery.namespace}