spring:
  application:
    name: i-boot3

  profiles:
    include:
      - dubbo
      - nacos
      - redis
      - datasource
      - mybatis

  cloud:
    compatibility-verifier:
      enabled: false