spring:
  config:
    import: optional:nacos:iboot-3.appplication.yml
  cloud:
    nacos:
      username: nacos
      password: nacos
      server-addr: ${nacos.address:192.168.145.133}:8848
      config:
        namespace: public
      discovery:
        namespace: public